The issue:

> FAIL: result code mismatch. Tx deploy. Want: 0. Have: 9 (contract invalid)

was fixed by installing the latest vmtools

```
Seems like there's a bug in how erdpy gets its latest vm release. Try this:
erdpy config set dependencies.vmtools.tag v1.4.26
erdpy deps install vmtools --overwrite
erdpy config delete dependencies.vmtools.tag
```
